import { CheckCircle2, Cloud, Cpu, KeyRound, Link2, ShieldCheck, Trash2, Unplug } from 'lucide-react';
import { useEffect, useState } from 'react';
import { deleteSecret, geminiCliStatus, isVisionDesktop, loadAssistantPreferences, saveAssistantPreferences, secretStatus, setSecret, type AssistantPreferences } from './assistantBridge';

export function VisionAISettings({ language }: { language: 'es' | 'en' }) {
  const es = language === 'es';
  const [prefs, setPrefs] = useState<AssistantPreferences>(loadAssistantPreferences);
  const [nvidiaKey, setNvidiaKey] = useState('');
  const [geminiKey, setGeminiKey] = useState('');
  const [nvidiaConfigured, setNvidiaConfigured] = useState(false);
  const [geminiConfigured, setGeminiConfigured] = useState(false);
  const [geminiCli, setGeminiCli] = useState<{ installed: boolean; version?: string; binary?: string; error?: string }>({ installed: false });
  const [message, setMessage] = useState('');
  const desktop = isVisionDesktop();

  const refresh = async () => {
    const [nvidia, gemini, cli] = await Promise.all([
      secretStatus('nvidia'),
      secretStatus('gemini-api'),
      geminiCliStatus(),
    ]);
    setNvidiaConfigured(Boolean(nvidia.configured));
    setGeminiConfigured(Boolean(gemini.configured));
    setGeminiCli(cli);
  };

  useEffect(() => { void refresh(); }, []);
  useEffect(() => { saveAssistantPreferences(prefs); }, [prefs]);

  const saveKey = async (provider: 'nvidia' | 'gemini-api', value: string) => {
    try {
      await setSecret(provider, value);
      if (provider === 'nvidia') setNvidiaKey(''); else setGeminiKey('');
      setMessage(es ? 'Credencial guardada en el llavero del sistema.' : 'Credential saved in the system keychain.');
      await refresh();
    } catch (reason) { setMessage(reason instanceof Error ? reason.message : String(reason)); }
  };
  const removeKey = async (provider: 'nvidia' | 'gemini-api') => {
    try { await deleteSecret(provider); setMessage(es ? 'Credencial eliminada.' : 'Credential removed.'); await refresh(); } catch (reason) { setMessage(reason instanceof Error ? reason.message : String(reason)); }
  };

  return <section className="vision-ai-settings-v2">
    <header className="ai-settings-head"><div><span className="micro">AI / PROVIDER SETTINGS</span><h1>{es ? 'Conexiones, modelos y credenciales.' : 'Connections, models and credentials.'}</h1><p>{es ? 'El asistente y el creador comparten un registro de providers, pero no son la misma cosa: el asistente razona y propone; el creador ejecuta generación sólo cuando el modelo y la capacidad están validados.' : 'The assistant and creator share a provider registry, but they are not the same thing: the assistant reasons and proposes; the creator executes generation only after model and capability validation.'}</p></div><div className={`desktop-state ${desktop ? 'ready' : ''}`}>{desktop ? <ShieldCheck size={17}/> : <Unplug size={17}/>}<div><strong>{desktop ? (es ? 'Desktop seguro' : 'Secure desktop') : 'PWA / Browser'}</strong><span>{desktop ? (es ? 'Keys en Keychain; nunca en el proyecto.' : 'Keys in Keychain; never in project data.') : (es ? 'La PWA usa un gateway cloud; las master keys nunca van al navegador.' : 'The PWA uses a cloud gateway; master keys never enter the browser.')}</span></div></div></header>

    <div className="ai-settings-grid">
      <article className="provider-settings-card featured"><div className="provider-card-title"><span className="provider-mark">N</span><div><span className="micro">ASSISTANT + SEMANTIC AI</span><h2>NVIDIA NIM</h2></div><em className={nvidiaConfigured ? 'connected' : ''}>{desktop ? (nvidiaConfigured ? (es ? 'Configurado' : 'Configured') : (es ? 'Sin key' : 'No key')) : (prefs.cloudGateway ? (es ? 'Vía cloud' : 'Via cloud') : (es ? 'Sin gateway' : 'No gateway'))}</em></div><p>{es ? 'Se usa para el chat/coproductor, crítica de prompts, propuestas de referencias y análisis semántico. La generación visual sigue separada por modelo/capacidad.' : 'Used for chat/copilot, prompt critique, reference suggestions and semantic analysis. Visual generation remains separated by model/capability.'}</p><label><span>{es ? 'API key NVIDIA' : 'NVIDIA API key'}</span><div className="secret-row"><input type="password" autoComplete="off" value={nvidiaKey} onChange={(event) => setNvidiaKey(event.target.value)} placeholder={nvidiaConfigured ? '••••••••••••••••' : 'nvapi-…'} disabled={!desktop}/><button type="button" disabled={!desktop || !nvidiaKey.trim()} onClick={() => void saveKey('nvidia', nvidiaKey)}><KeyRound size={14}/>{nvidiaConfigured ? (es ? 'Reemplazar' : 'Replace') : (es ? 'Guardar' : 'Save')}</button>{nvidiaConfigured && <button className="danger" type="button" onClick={() => void removeKey('nvidia')}><Trash2 size={14}/></button>}</div></label><label><span>{es ? 'Modelo para el asistente' : 'Assistant model'}</span><input value={prefs.nvidiaModel} onChange={(event) => setPrefs((current) => ({ ...current, nvidiaModel: event.target.value }))} placeholder="meta/muse-glimmer-30b"/></label><label><span>Endpoint</span><input value={prefs.nvidiaEndpoint} onChange={(event) => setPrefs((current) => ({ ...current, nvidiaEndpoint: event.target.value }))}/></label><small>{es ? 'Desktop usa Keychain. PWA usa el Cloud Gateway configurado abajo. Vision no asume que un modelo sea gratis o mantenga siempre la misma capacidad.' : 'Desktop uses Keychain. PWA uses the Cloud Gateway configured below. Vision never assumes a model remains free or keeps the same capability forever.'}</small></article>

      <article className="provider-settings-card"><div className="provider-card-title"><span className="provider-mark"><Cloud size={16}/></span><div><span className="micro">PWA BACKEND</span><h2>Vision Cloud Gateway</h2></div><em className={prefs.cloudGateway ? 'connected' : ''}>{prefs.cloudGateway ? (es ? 'Configurado' : 'Configured') : (es ? 'Opcional' : 'Optional')}</em></div><p>{es ? 'Endpoint seguro para que la PWA use Copilot y, cuando se habiliten adapters, jobs de generación sin exponer claves maestras en GitHub Pages.' : 'Secure endpoint that lets the PWA use Copilot and, once adapters are enabled, generation jobs without exposing master keys in GitHub Pages.'}</p><label><span>Gateway URL</span><div className="secret-row"><input value={prefs.cloudGateway} onChange={(event) => setPrefs((current) => ({ ...current, cloudGateway: event.target.value }))} placeholder="https://REGION-PROJECT.cloudfunctions.net/visionGateway"/><span className="endpoint-icon"><Link2 size={15}/></span></div></label><small>{es ? 'Debe usar HTTPS. Firebase Functions/Cloud Run es la ruta recomendada; App Check/Auth se configuran en el backend.' : 'Must use HTTPS. Firebase Functions/Cloud Run is the recommended route; App Check/Auth are configured in the backend.'}</small></article>

      <article className="provider-settings-card"><div className="provider-card-title"><span className="provider-mark">G</span><div><span className="micro">ASSISTANT ENGINE</span><h2>{desktop ? 'Gemini CLI' : 'Gemini Cloud'}</h2></div><em className={desktop && geminiCli.installed ? 'connected' : ''}>{desktop ? (geminiCli.installed ? (es ? 'Detectado' : 'Detected') : (es ? 'No detectado' : 'Not detected')) : (prefs.cloudGateway ? (es ? 'Vía gateway' : 'Via gateway') : (es ? 'Sin gateway' : 'No gateway'))}</em></div><p>{desktop ? (es ? 'Opción local para el mejorador/chat usando la autenticación del CLI. Vision lo llama en modo headless con salida JSON y sin convertirlo en el dueño del proyecto.' : 'Local option for the improver/chat using CLI authentication. Vision invokes it headlessly with JSON output without making it the owner of project state.') : (es ? 'En la PWA, Gemini pasa por el Cloud Gateway para que las credenciales permanezcan del lado servidor.' : 'In the PWA, Gemini goes through the Cloud Gateway so credentials stay server-side.')}</p><label><span>{es ? 'Modelo opcional' : 'Optional model'}</span><input value={prefs.geminiModel} onChange={(event) => setPrefs((current) => ({ ...current, geminiModel: event.target.value }))} placeholder={es ? 'vacío = modelo por defecto' : 'blank = default model'}/></label>{desktop && geminiCli.binary && <small>{geminiCli.binary}{geminiCli.version ? ` · ${geminiCli.version}` : ''}</small>}{desktop && geminiCli.error && <small>{geminiCli.error}</small>}</article>

      <article className="provider-settings-card"><div className="provider-card-title"><span className="provider-mark">G</span><div><span className="micro">DIRECT API · DESKTOP</span><h2>Gemini API</h2></div><em className={geminiConfigured ? 'connected' : ''}>{geminiConfigured ? (es ? 'Key guardada' : 'Key stored') : (es ? 'Preparado' : 'Prepared')}</em></div><p>{es ? 'Slot separado del Gemini CLI. Se conserva independiente para elegir autenticación y modelos sin mezclarlos.' : 'Separate slot from Gemini CLI. It stays independent so authentication and model selection do not get mixed.'}</p><label><span>Gemini API key</span><div className="secret-row"><input type="password" autoComplete="off" value={geminiKey} onChange={(event) => setGeminiKey(event.target.value)} placeholder={geminiConfigured ? '••••••••••••••••' : 'AIza…'} disabled={!desktop}/><button type="button" disabled={!desktop || !geminiKey.trim()} onClick={() => void saveKey('gemini-api', geminiKey)}><KeyRound size={14}/>{geminiConfigured ? (es ? 'Reemplazar' : 'Replace') : (es ? 'Guardar' : 'Save')}</button>{geminiConfigured && <button className="danger" type="button" onClick={() => void removeKey('gemini-api')}><Trash2 size={14}/></button>}</div></label><small>{es ? 'La ejecución directa se anuncia sólo después de pasar adapter + pruebas; la PWA no almacena esta key.' : 'Direct execution is advertised only after adapter + tests pass; the PWA never stores this key.'}</small></article>

      <article className="provider-settings-card"><div className="provider-card-title"><span className="provider-mark">C</span><div><span className="micro">LOCAL GENERATION</span><h2>ComfyUI</h2></div><em>{desktop ? (es ? 'Desktop local' : 'Desktop local') : (es ? 'Requiere bridge' : 'Requires bridge')}</em></div><p>{es ? 'ComfyUI pertenece al módulo de creación: Vision compila intención y parámetros; el connector descubre workflow, nodos y modelos antes de enviar un job.' : 'ComfyUI belongs to the creation module: Vision compiles intent and parameters; the connector discovers workflow, nodes and models before submitting a job.'}</p><label><span>{es ? 'Endpoint local' : 'Local endpoint'}</span><div className="secret-row"><input value={prefs.comfyEndpoint} onChange={(event) => setPrefs((current) => ({ ...current, comfyEndpoint: event.target.value }))}/><span className="endpoint-icon"><Link2 size={15}/></span></div></label><small>{es ? 'Desktop puede hablar con localhost de forma controlada. La PWA pública no depende de localhost por restricciones de CORS/Private Network y iOS.' : 'Desktop can talk to localhost in a controlled way. The public PWA does not depend on localhost because of CORS/Private Network and iOS restrictions.'}</small></article>
    </div>

    <section className="provider-boundary"><Cpu size={18}/><div><strong>{es ? 'Separación correcta de responsabilidades' : 'Correct separation of responsibilities'}</strong><p>{es ? 'Copilot / Mejorador = conversar, analizar, criticar y proponer patches. Creator / Generate = seleccionar provider/model/workflow, hacer preflight, mostrar requisitos/coste si existe y ejecutar sólo con acción explícita. Así el botón Generar aparece cuando realmente hay una ruta ejecutable.' : 'Copilot / Improver = converse, analyze, critique and propose patches. Creator / Generate = select provider/model/workflow, run preflight, show requirements/cost when available and execute only on explicit action. This is when the Generate button should become enabled.'}</p></div></section>
    {message && <div className="settings-toast"><CheckCircle2 size={15}/>{message}</div>}
  </section>;
}
